'use strict';
const assert = require('node:assert/strict');
const { GameServer } = require('./game');
const g = new GameServer();
const a = g.addPlayer('Alpha');
const b = g.addPlayer('Beta');
a.cells[0].mass = 500; b.cells[0].mass = 100;
a.target={x:b.cells[0].x,y:b.cells[0].y};
b.target={x:a.cells[0].x,y:a.cells[0].y};
assert.equal(g.markTarget(a,b.id),true);
assert.equal(g.parry(a),true);
assert.ok(g.getWallet(a).coins >= 0);
assert.ok(g.getCatalog().length >= 8);
assert.ok(g.getQuests(a).length >= 4);
a.dailyClaimAt = 0;
assert.equal(g.claimDailyReward(a),true);
assert.equal(g.adminSetMass(a.id,300),true);
assert.equal(g.adminSetCoins(a.id,5000),true);
assert.equal(g.adminSetColor(a.id,'#123456'),true);
assert.equal(g.adminSpawnBots(3,30,'aggressive'),3);
assert.equal(g.adminSetBotDifficulty(4),4);
assert.equal(g.buyItem(a,'skin_galaxy'),true);
assert.equal(g.isOwned(a,'skin_galaxy'),true);
assert.equal(g.equipItem(a,'skin_galaxy'),true);
assert.equal(g.refundLastPurchase(a),true);
for(let i=0;i<30;i++) g.tick();
assert.ok(g.pvpLeaderboard(10).length>=1);
const snap = g.snapshotFor(a);
assert.ok(Array.isArray(snap.traps)); assert.ok(Array.isArray(snap.mines)); assert.ok(snap.wallet && typeof snap.wallet.coins === 'number'); assert.ok(Array.isArray(snap.quests));
assert.ok(g.performanceStats().totalTicks>=30);
console.log('90 FEATURE TEST OK');
