CREATE TABLE IF NOT EXISTS zl_user_preferences (
  user_id INT UNSIGNED NOT NULL,
  settings_json LONGTEXT NOT NULL,
  keybinds_json LONGTEXT NOT NULL,
  skin_color VARCHAR(20) NOT NULL DEFAULT '#4dd0ff',
  nickname VARCHAR(40) NOT NULL DEFAULT '',
  custom_skin_url VARCHAR(500) NULL,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (user_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS zl_custom_skins (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  user_id INT UNSIGNED NOT NULL,
  name VARCHAR(100) NOT NULL,
  url VARCHAR(500) NOT NULL,
  mime VARCHAR(80) NOT NULL DEFAULT 'image/gif',
  size_bytes INT UNSIGNED NOT NULL DEFAULT 0,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id), INDEX idx_skin_user (user_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
