<?php
declare(strict_types=1);
header('Content-Type: application/json; charset=utf-8');
header('Cache-Control: no-store');
if (($_SERVER['REQUEST_METHOD'] ?? 'GET') === 'OPTIONS') { http_response_code(204); exit; }
require_once __DIR__ . '/auth/db-config.php';
function out(array $x, int $s=200): void { http_response_code($s); echo json_encode($x, JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES); exit; }
function body(): array { $raw=file_get_contents('php://input'); $j=json_decode($raw ?: '', true); return is_array($j)?$j:$_POST; }
function schema(): void {
  db()->exec("CREATE TABLE IF NOT EXISTS zl_shop_items(id INT UNSIGNED NOT NULL AUTO_INCREMENT, item_key VARCHAR(64) NOT NULL UNIQUE, name VARCHAR(100) NOT NULL, description VARCHAR(255) NOT NULL, price INT UNSIGNED NOT NULL DEFAULT 0, category VARCHAR(30) NOT NULL DEFAULT 'cosmetic', PRIMARY KEY(id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4");
  db()->exec("CREATE TABLE IF NOT EXISTS zl_inventory(user_id INT UNSIGNED NOT NULL, item_key VARCHAR(64) NOT NULL, quantity INT UNSIGNED NOT NULL DEFAULT 1, equipped TINYINT(1) NOT NULL DEFAULT 0, updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, PRIMARY KEY(user_id,item_key)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4");
  db()->exec("CREATE TABLE IF NOT EXISTS zl_daily_claims(user_id INT UNSIGNED NOT NULL, claim_date DATE NOT NULL, reward INT UNSIGNED NOT NULL, PRIMARY KEY(user_id,claim_date)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4");
  $items=[['skin_neon','Neon Skin','Effetto neon per il profilo',300,'cosmetic'],['skin_galaxy','Galaxy Skin','Skin galattica',500,'cosmetic'],['boost_xp','XP Booster','Bonus XP per le partite',250,'boost'],['boost_coins','Coin Booster','Bonus Coins per le partite',250,'boost'],['shield_pack','Shield Pack','Pacchetto scudi',400,'powerup'],['starter_bundle','Starter Bundle','Bundle cosmetico e boost',750,'bundle']];
  $st=db(); $q=$st->prepare('INSERT IGNORE INTO zl_shop_items(item_key,name,description,price,category) VALUES(?,?,?,?,?)'); foreach($items as $it)$q->execute($it);
}
function token_user(string $token): ?array { if($token==='')return null; $parts=explode('.', $token); if(count($parts)!==2)return null; [$p,$sig]=$parts; if(!defined('API_SECRET') || !hash_equals(hash_hmac('sha256',$p,(string)API_SECRET),$sig))return null; $d=json_decode(base64_decode(strtr($p,'-_','+/')),true); if(!is_array($d)||($d['exp']??0)<time())return null; $st=db()->prepare('SELECT id,email,full_name FROM zl_users WHERE id=?'); $st->execute([(int)($d['uid']??0)]); return $st->fetch() ?: null; }
function profile(int $uid): array { $st=db()->prepare('SELECT coins,xp,level,games_played,best_mass,best_rank,kills,deaths,elo FROM zl_profiles WHERE user_id=?'); $st->execute([$uid]); return $st->fetch() ?: ['coins'=>0,'xp'=>0,'level'=>1,'games_played'=>0,'best_mass'=>0,'best_rank'=>null,'kills'=>0,'deaths'=>0,'elo'=>1000]; }
schema(); $b=body(); $action=(string)($b['action']??($_GET['action']??''));
if($action==='health') out(['ok'=>true,'service'=>'portal','database'=>'ok']);
$u=token_user((string)($b['token']??'')); if(!$u) out(['ok'=>false,'error'=>'Autenticazione richiesta.'],401); $uid=(int)$u['id'];
if($action==='profile'){ out(['ok'=>true,'user'=>['id'=>$uid,'email'=>$u['email'],'name'=>$u['full_name']],'profile'=>profile($uid)]); }
if($action==='shop'){ $items=db()->query('SELECT item_key,name,description,price,category FROM zl_shop_items ORDER BY price')->fetchAll(); $st=db()->prepare('SELECT item_key,quantity,equipped FROM zl_inventory WHERE user_id=?'); $st->execute([$uid]); out(['ok'=>true,'items'=>$items,'inventory'=>$st->fetchAll(),'profile'=>profile($uid)]); }
if($action==='buy'){ $key=(string)($b['item_key']??''); $st=db()->prepare('SELECT * FROM zl_shop_items WHERE item_key=?'); $st->execute([$key]); $item=$st->fetch(); if(!$item)out(['ok'=>false,'error'=>'Oggetto non trovato.'],404); $pdo=db(); $pdo->beginTransaction(); try{ $st=$pdo->prepare('SELECT coins FROM zl_profiles WHERE user_id=? FOR UPDATE');$st->execute([$uid]);$p=$st->fetch(); if(!$p||((int)$p['coins']<(int)$item['price'])){ $pdo->rollBack(); out(['ok'=>false,'error'=>'Coins insufficienti.'],400);} $pdo->prepare('UPDATE zl_profiles SET coins=coins-? WHERE user_id=?')->execute([(int)$item['price'],$uid]); $pdo->prepare('INSERT INTO zl_inventory(user_id,item_key,quantity) VALUES(?,?,1) ON DUPLICATE KEY UPDATE quantity=quantity+1')->execute([$uid,$key]); $pdo->commit(); out(['ok'=>true,'message'=>'Acquisto completato.','profile'=>profile($uid)]);}catch(Throwable $e){$pdo->rollBack();out(['ok'=>false,'error'=>'Acquisto non riuscito.'],500);} }
if($action==='equip'){ $key=(string)($b['item_key']??''); $pdo=db(); $pdo->prepare('UPDATE zl_inventory SET equipped=0 WHERE user_id=?')->execute([$uid]); $st=$pdo->prepare('UPDATE zl_inventory SET equipped=1 WHERE user_id=? AND item_key=?');$st->execute([$uid,$key]); if(!$st->rowCount())out(['ok'=>false,'error'=>'Oggetto non posseduto.'],400); out(['ok'=>true,'profile'=>profile($uid)]); }
if($action==='daily'){ $today=date('Y-m-d'); $st=db()->prepare('SELECT 1 FROM zl_daily_claims WHERE user_id=? AND claim_date=?');$st->execute([$uid,$today]);if($st->fetch())out(['ok'=>false,'error'=>'Bonus già riscosso oggi.'],400); $reward=100; db()->beginTransaction(); try{db()->prepare('INSERT INTO zl_daily_claims(user_id,claim_date,reward) VALUES(?,?,?)')->execute([$uid,$today,$reward]);db()->prepare('UPDATE zl_profiles SET coins=coins+?, xp=xp+20 WHERE user_id=?')->execute([$reward,$uid]);db()->commit();out(['ok'=>true,'reward'=>$reward,'profile'=>profile($uid)]);}catch(Throwable $e){db()->rollBack();out(['ok'=>false,'error'=>'Bonus non disponibile.'],500);} }
if($action==='leaderboard'){ $rows=db()->query('SELECT u.full_name,p.level,p.xp,p.coins,p.kills,p.elo FROM zl_profiles p JOIN zl_users u ON u.id=p.user_id ORDER BY p.elo DESC,p.xp DESC LIMIT 20')->fetchAll(); out(['ok'=>true,'rows'=>$rows]); }
out(['ok'=>false,'error'=>'Azione sconosciuta.'],400);
