(() => {
  'use strict';
  const $ = id => document.getElementById(id);
  const API = '/portal-api.php';
  const toast = m => { const t=$('toast'); if(!t)return; t.textContent=m; t.classList.add('show'); clearTimeout(window.__zt); window.__zt=setTimeout(()=>t.classList.remove('show'),2600); };
  async function api(action, payload={}) {
    const token = window.ZLAuth?.getToken?.() || '';
    const r = await fetch(API,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action,token,...payload}),cache:'no-store'});
    const d=await r.json().catch(()=>({ok:false,error:'Risposta non valida'})); if(!r.ok||!d.ok) throw new Error(d.error||`HTTP ${r.status}`); return d;
  }
  const money=n=>Number(n||0).toLocaleString('it-IT');
  function renderProfile(d){ const u=d.user,p=d.profile; $('profileName').textContent=u.name; $('profileEmail').textContent=u.email; $('avatar').textContent=(u.name||'Z').slice(0,1).toUpperCase(); $('heroLevel').textContent=p.level; $('heroCoins').textContent=money(p.coins); $('heroGames').textContent=p.games_played; $('statCoins').textContent=money(p.coins); $('statGames').textContent=p.games_played; $('statKills').textContent=p.kills; $('statBestMass').textContent=p.best_mass; $('statElo').textContent=p.elo; $('shopCoins').textContent=money(p.coins); const need=p.level*100; $('xpText').textContent=`${p.xp%100} / ${need} XP`; $('levelText').textContent=`Lv. ${p.level}`; $('xpBar').style.width=`${Math.min(100,(p.xp%100)/need*100)}%`; }
  async function loadProfile(){ try{const d=await api('profile'); renderProfile(d); $('account').classList.remove('hidden'); $('authCard').classList.add('hidden'); $('logoutBtn').classList.remove('hidden'); $('authStatus').textContent=`Connesso come ${d.user.name}`;}catch(_){ $('account').classList.add('hidden'); $('authCard').classList.remove('hidden'); $('logoutBtn').classList.add('hidden'); $('authStatus').textContent='Non autenticato'; } }
  async function loadShop(){ try{const d=await api('shop'); renderProfile({user:window.ZLAuth.getUser()||{name:'Giocatore',email:''},profile:d.profile}); const inv=new Map(d.inventory.map(x=>[x.item_key,x])); $('shopGrid').innerHTML=d.items.map(i=>{const have=inv.get(i.item_key);return `<article class="shop-item"><div class="tag">${i.category}</div><h3>${i.name}</h3><p class="muted">${i.description}</p><div class="price">🪙 ${money(i.price)}</div><button class="secondary-btn buy" data-key="${i.item_key}">${have?`Posseduto x${have.quantity}`:'Acquista'}</button>${have?`<button class="secondary-btn equip" data-key="${i.item_key}">${have.equipped?'✅ Equipaggiato':'Equipaggia'}</button>`:''}</article>`}).join(''); document.querySelectorAll('.buy').forEach(b=>b.onclick=async()=>{try{await api('buy',{item_key:b.dataset.key});toast('✅ Acquisto completato');loadShop()}catch(e){toast('❌ '+e.message)}});document.querySelectorAll('.equip').forEach(b=>b.onclick=async()=>{try{await api('equip',{item_key:b.dataset.key});toast('✅ Oggetto equipaggiato');loadShop()}catch(e){toast('❌ '+e.message)}});}catch(e){toast('❌ '+e.message)} }
  async function loadLeaderboard(){ try{const d=await api('leaderboard');$('leaderboard').innerHTML=d.rows.length?d.rows.map((r,i)=>`<div class="leader-row"><span>${i+1}</span><span>${r.full_name} · Lv.${r.level}</span><b>${r.elo} ELO</b></div>`).join(''):'<div class="muted">Nessun giocatore ancora.</div>';}catch(_){$('leaderboard').innerHTML='<div class="muted">Accedi per vedere la classifica.</div>';} }
  function setupTabs(){document.querySelectorAll('.auth-tab').forEach(b=>b.onclick=()=>{document.querySelectorAll('.auth-tab').forEach(x=>x.classList.remove('active'));b.classList.add('active');const reg=b.dataset.tab==='register';$('loginForm').classList.toggle('hidden',reg);$('registerForm').classList.toggle('hidden',!reg);});}
  $('logoutBtn').onclick=()=>window.ZLAuth?.logout?.(); $('openProfile').onclick=()=>{$('profileModal').classList.remove('hidden');const d=window.ZLAuth.getUser()||{};$('profileDetail').innerHTML=`<p><b>${d.name||'Giocatore'}</b><br>${d.email||''}</p><p>Il profilo completo e lo stato Coins sono sincronizzati con il database.</p>`}; document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>$('profileModal').classList.add('hidden')); $('heroShopBtn').onclick=()=>document.querySelector('#shop').scrollIntoView({behavior:'smooth'}); $('dailyBtn').onclick=async()=>{try{const d=await api('daily');toast(`🎁 +${d.reward} Coins`);renderProfile({user:window.ZLAuth.getUser(),profile:d.profile});}catch(e){toast('❌ '+e.message)}};
  window.addEventListener('auth-changed',()=>{loadProfile();loadShop();loadLeaderboard();}); document.addEventListener('DOMContentLoaded',()=>{setupTabs();setTimeout(()=>{loadProfile();loadShop();loadLeaderboard();},80);});
})();
