<?php
declare(strict_types=1);
header('Content-Type: application/json; charset=utf-8');
header('Cache-Control: no-store');
require_once __DIR__ . '/../auth/db-config.php';
require_once __DIR__ . '/config.php';
function out(array $d,int $s=200): void { http_response_code($s); echo json_encode($d,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES); exit; }
function body(): array { $r=file_get_contents('php://input'); $j=is_string($r)?json_decode($r,true):null; return is_array($j)?$j:(is_array($_POST)?$_POST:[]); }
function b64u(string $s): string { return rtrim(strtr(base64_encode($s),'+/','-_'),'='); }
function b64d(string $s) { $p=strlen($s)%4; if($p)$s.=str_repeat('=',4-$p); return base64_decode(strtr($s,'-_','+/'),true); }
function token_user(string $token): ?array { if(!defined('API_SECRET')||!API_SECRET)return null; $p=explode('.',trim($token)); if(count($p)!==3||$p[0]!=='zl1')return null; $sig=b64u(hash_hmac('sha256',$p[1],(string)API_SECRET,true)); if(!hash_equals($sig,$p[2]))return null; $j=b64d($p[1]); if($j===false)return null; $x=json_decode($j,true); if(!is_array($x)||(int)($x['exp']??0)<time())return null; $s=db()->prepare('SELECT * FROM users WHERE id=? LIMIT 1'); $s->execute([(int)($x['uid']??0)]); return $s->fetch() ?: null; }
function stripe_post(string $key,array $fields): array { $ch=curl_init('https://api.stripe.com/v1/checkout/sessions'); curl_setopt_array($ch,[CURLOPT_RETURNTRANSFER=>true,CURLOPT_POST=>true,CURLOPT_USERPWD=>$key.':',CURLOPT_HTTPHEADER=>['Content-Type: application/x-www-form-urlencoded'],CURLOPT_POSTFIELDS=>http_build_query($fields),CURLOPT_TIMEOUT=>15]); $raw=curl_exec($ch); $code=(int)curl_getinfo($ch,CURLINFO_HTTP_CODE); $err=curl_error($ch); curl_close($ch); if($raw===false) return ['ok'=>false,'error'=>$err?:'Stripe connection error']; $data=json_decode($raw,true); return ['ok'=>$code>=200&&$code<300,'status'=>$code,'data'=>is_array($data)?$data:[]]; }
if(($_SERVER['REQUEST_METHOD']??'POST')!=='POST')out(['ok'=>false,'error'=>'POST richiesto.'],405);
if(STRIPE_SECRET_KEY==='INSERISCI_STRIPE_SECRET_KEY')out(['ok'=>false,'error'=>'Stripe non configurato: inserisci STRIPE_SECRET_KEY.'],503);
$b=body(); $u=token_user((string)($b['token']??'')); if(!$u)out(['ok'=>false,'error'=>'Sessione non valida.'],401);
$packages=coin_packages(); $pkg=(string)($b['package']??'zc_1000'); if(!isset($packages[$pkg]))out(['ok'=>false,'error'=>'Pacchetto non valido.'],400); $p=$packages[$pkg];
$db=db(); $db->exec("CREATE TABLE IF NOT EXISTS zl_coin_orders (id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,user_id INT UNSIGNED NOT NULL,package_id VARCHAR(40) NOT NULL,coins INT NOT NULL,amount_cents INT NOT NULL,currency VARCHAR(10) NOT NULL,stripe_session_id VARCHAR(255) NULL,stripe_payment_intent VARCHAR(255) NULL,status VARCHAR(30) NOT NULL DEFAULT 'pending',webhook_event_id VARCHAR(255) NULL,created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,paid_at TIMESTAMP NULL,PRIMARY KEY(id),UNIQUE KEY uq_session(stripe_session_id),UNIQUE KEY uq_event(webhook_event_id),INDEX idx_order_user(user_id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci");
$st=$db->prepare('INSERT INTO zl_coin_orders(user_id,package_id,coins,amount_cents,currency,status) VALUES(?,?,?,?,?,?)'); $st->execute([(int)$u['id'],$pkg,(int)$p['coins'],(int)$p['amount'],PAYMENT_CURRENCY,'pending']); $order=(int)$db->lastInsertId();
$fields=['mode'=>'payment','success_url'=>PORTAL_BASE_URL.'/payment-success.html?session_id={CHECKOUT_SESSION_ID}','cancel_url'=>PORTAL_BASE_URL.'/?payment=cancelled','client_reference_id'=>'zl-order-'.$order,'customer_email'=>(string)$u['email'],'line_items[0][price_data][currency]'=>PAYMENT_CURRENCY,'line_items[0][price_data][product_data][name]'=>$p['name'],'line_items[0][price_data][product_data][description]'=>'ZeroLegend virtual currency','line_items[0][price_data][unit_amount]'=>(int)$p['amount'],'line_items[0][quantity]'=>1,'metadata[order_id]'=>$order,'metadata[user_id]'=>(int)$u['id'],'metadata[package_id]'=>$pkg,'metadata[coins]'=>$p['coins'],'locale'=>'it'];
$r=stripe_post(STRIPE_SECRET_KEY,$fields); if(!$r['ok']){ $db->prepare('UPDATE zl_coin_orders SET status=? WHERE id=?')->execute(['error',$order]); out(['ok'=>false,'error'=>(string)($r['data']['error']['message']??$r['error']??'Stripe error')],502); }
$sid=(string)($r['data']['id']??''); $db->prepare('UPDATE zl_coin_orders SET stripe_session_id=? WHERE id=?')->execute([$sid,$order]); out(['ok'=>true,'url'=>(string)($r['data']['url']??''),'session_id'=>$sid,'order_id'=>$order]);
